version: '3'

services:
  phpipam-nginx:
    image: nixit89/phpipam-ngpf:latest
    ports:
      - "80:80"
    environment:
      - MODE=nginx
      - TZ=Asia/Vladivostok
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=dbuserpass
      - IPAM_DATABASE_WEBHOST=%
      - PHP_FPM_HOST=phpipam-fpm
    restart: unless-stopped
    volumes:
      - phpipam-ngpf-ipam:/phpipam
    links:
      - phpipam-fpm
    depends_on:
      - phpipam-mariadb

  phpipam-fpm:
    image: nixit89/phpipam-ngpf:latest
    environment:
      - MODE=php-fpm
      - TZ=Asia/Vladivostok
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=dbuserpass
      - IPAM_DATABASE_WEBHOST=%
    volumes:
      - phpipam-ngpf-ipam:/phpipam
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: nixit89/phpipam-ngpf-cron:v1.5.0
    environment:
      - TZ=Asia/Vladivostok
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=dbuserpass
      - SCAN_INTERVAL=5m
    restart: unless-stopped
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=dbrootpass
      - TZ=Asia/Vladivostok
    restart: unless-stopped
    volumes:
      - phpipam-ngpf-db-data:/var/lib/mysql

volumes:
  phpipam-ngpf-db-data:
  phpipam-ngpf-ipam:








